# Generated by Django 5.2.7 on 2025-11-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_spectrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedsignal',
            name='spectrum_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
