# Generated by Django 5.2.7 on 2026-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
