# Generated by Django 5.2.7 on 2025-11-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedaudio',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='Pending', max_length=20),
        ),
    ]
